---
title: "ARPE19"
output:
  word_document: default
  html_document:
    df_print: paged
---

install.packages("rmarkdown")

```{r include=F}
knitr::opts_chunk$set (echo=F)
```

```{r packages}
#install.packages('shinydashboard')
# install.packages('rsconnect')
# rsconnect::setAccountInfo(name='rromain-10', 
#                           token='708AE86DD216401F0304DE58972E2A49', 
#                           secret='B+AAnRaJVGVFzu98RU3u6LXF7cVqeSSVmk4YJqOE')
# library(rsconnect)
# getwd()
#rsconnect::deployApp('/Users/romarioromain/OneDrive - Colostate/RR_ARPE_DELUCA_COLLAB/Rshiny/2_app.R')

library(shiny)
library(ggplot2)
library(reshape2)
library(datasets)
library(dplyr)
library(RColorBrewer)
library(pheatmap)
library(DESeq2)
library(shinydashboard)
```



```{r Inputs and outputs}
ui<- fluidPage(
  titlePanel("ARPE19 progression data view"),
  
  fluidRow(
    
      column(3, 
             plotOutput('MAplot1')
            ),
      
      column (3,
              plotOutput('MAplot2')
              ),
     
     column(3,
            plotOutput('MAplot3')
            ),
     
     column(3,
            plotOutput('MAplot4')
            )
  ),
  
  #heatmap for Genes of interest
  dashboardBody(
    sidebarLayout(
      sidebarPanel(
  
        #heatmap for Genes of interest
        checkboxGroupInput(inputId = "Gene",
                           label = " Choose Gene of Interest",
                           selected=unlist(strsplit('AURKB NUF2 PPP1CB PPP1CC PPP2R5B PPP2R5D SGO1 SKA1',
                                                    split=' ')),
                           unlist(strsplit('AURKB NUF2 PPP1CB PPP1CC PPP2R5B PPP2R5D SGO1 SKA1',
                                           split=' ')
                           )
        ),
        
        checkboxGroupInput(inputId = "sample", label = " Choose sample", selected=c("ARPE19","RasV12"),
                           c("ARPE19", "T53D4", "RasV12","Aktmyr" ,"MekDD")
                          )
        ),
      mainPanel(
        plotOutput('pheatmap1')
            )
    )
   ),
  
  #heatmap for significantly changing genes 
  dashboardBody(
      sidebarLayout(
      sidebarPanel(
        
         checkboxGroupInput(inputId = "sample1", label = " Choose sample", choices =     
                           c("ARPE19", "T53D4", "RasV12","Aktmyr" ,"MekDD"),
                           selected=c("ARPE19","RasV12"),
        ),
        
        conditionalPanel(condition = "output.nrows"),
        selectInput(inputId = "All",
                    label = "Select genes from all signficantly changing genes",
                    choices = means_of_changing_genes$X
                   )
        ),
  mainPanel(
    plotOutput('pheatmap2')
      )
    )
  ),
  #boxplot for significantly changing genes 
  dashboardBody(
    sidebarLayout(
      sidebarPanel(

        
        checkboxGroupInput(inputId = "Gene2", 
                           label = " Choose Gene ",
                          choices = c("AKT1" , "HRAS"),
                          selected = ("AKT1")
        )
      ),
  mainPanel(
    plotOutput('boxplot1')
          )
       )
     )
  )
  

```






```{r figures and displays}
server<- function(input,output, session) {
  session$onSessionEnded(stopApp);
  ##files needed
  goi_ncounts<- read.csv("DEseq2_means_goi_ncounts.csv");
  changing_lrt_rdl<- read.csv("changing_lrt_rdl.csv");
  genes_of_interest_means<- read.csv("genes_of_interest_means.csv");
  means_of_changing_genes<- read.csv("means_of_changing_genes.csv");
  ncounts_goi_no_genecol<- read.csv("ncounts_goi_no_genecol.csv");
  normalized_genecounts<- read.csv("normalized_genecounts.csv")
  dds<- readRDS("dds.RDS")
  dds$sample <- factor(dds$sample, levels=c("ARPE19", "T53D4", "RasV12", "Aktmyr", "MekDD"))
  dds$sample
  cts<- readRDS("cts.RDS")
  res_T53D4_vs_MekDD<- readRDS('res/res_T53D4_vs_MekDD.RDS')
  res_ARPE19_vs_T53D4<-readRDS ('res/res_ARPE19_vs_T53D4')
  res_ARPE19_vs_RasV12<- readRDS ('res/res_ARPE19_vs_Rasv12')
  res_ARPE19_vs_MekDD<- readRDS('res/res_ARPE19_vs_MekDD')
  res_ARPE19_vs_Aktmyr<- readRDS('res/res_ARPE19_vs_Aktmyr')
  selectedGenes = c('BUB1B','AURKB','BUB1','SKA1','SKA2','SKA3','SGO1','PPP2R5C',
                    'PPP2R5B','PPP2R2A','PPP2R2A','PPP2R5D','PPP2R5A','PPP2R5E',
                    'PPP1CA','PPP1CC','PPP1CB','HEC1','NUF2','SPC24','SPC25')
  #Gene associated with MEK pathway
  Mek_genes=c('MAP2K1', 'MAP2K2','MAP2K3','MAP2K4','MAP2K5','MAP2K6','MAP2K7',
              'PTPN11', 'GBR2','SOS1')
  
  #Gens associated with the RAS pathway
  Ras_genes=c('KRAS','NRAS','BRAF','HRAS','RAF1')
  
  #Gene associated with AKT pathway
  Akt_genes =c('AKT1','AKT2','AKT3','AKT8','PDK1','PDK2','MTOR')
  
  #Genes assocaited with T53D4
  T53D4_genes=c('CDK4', 'TP53')
  # 
  # library(GenomicFeatures)
  # library(ensembldb)
  # library(biomaRt)
  # ensembl = useDataset("hsapiens_gene_ensembl",mart=useMart("ENSEMBL_MART_ENSEMBL"))
  # ctsnames = rownames(cts)
  # 
  # # figure out filter,values,and attributes at http://www.ensembl.org/biomart/martview
  # gene_names = getBM(mart = ensembl, filter='ensembl_gene_id', value=ctsnames, attributes=c('external_gene_name', 'ensembl_gene_id'))
  # dim(gene_names) # 20002     2
  # length(ctsnames) # 20003
  # ctsnames = ctsnames[ ctsnames %in%  gene_names$ensembl_gene_id] # only one gene not found- ENSG00000254462, and it's all 0s
  # length(ctsnames) # 20002
  # rownames(gene_names) <- gene_names$ensembl_gene_id
  # gene_names = gene_names[ctsnames,]
  # cts=cts[rownames(cts) != 'ENSG00000254462',]# take out the 0 count gene
  # rownames(cts) <- gene_names$external_gene_name
    
  ({
  
    #MAplots ARPE19 vs T53D4 
    output$MAplot1 <- renderPlot ({
      print("rendering plot: MAplot ARPE19 vs T53D4")
      #ARPE19 vs T53D4 plots##
      par(mfrow=c(1,1))
      #print(input$sample1)
      plotMA(res_ARPE19_vs_T53D4, main="ARPE19 vs T53D4", ylim = c(-20,20),
             ylab = "log fold change (ratio of normalized ARPE19 / T53D4)",
             xlab = "means of normalized counts",
             cex.main= 2,
             cex= 0.5,
             alpha=0.5)
      # with(res_ARPE19_vs_T53D4 [selectedGenes, ],
      #      { points(baseMean,log2FoldChange, col= "dodgerblue", cex=1,
      #               lwd=2)
      #        text(baseMean,log2FoldChange,
      #             selectedGenes, pos=2, col="dodgerblue")})
      # with(res_ARPE19_vs_T53D4 [T53D4_genes, ],
      #      { points(baseMean,log2FoldChange, col= "dodgerblue", cex=1,
      #               lwd=2)
      #        text(baseMean,log2FoldChange, T53D4_genes, pos=2, col="dodgerblue")})
    })
       
    #MAplots ARPE19 vs RasV12    
    output$MAplot2 <- renderPlot ({
        print("rendering plot: MAplot ARPE19 vs RasV12")
         ##ARPE19 vs RasV12 plots##
         par(mfrow=c(1,1))
         #print(input$sample1)
         plotMA(res_ARPE19_vs_RasV12, main="ARPE19 vs RasV12", ylim = c(-20,20),
                ylab = "log fold change (ratio of normalized ARPE19 / RasV12)",
                xlab = "means of normalized counts",
                cex.main= 2,
                cex= 0.5,
                alpha= 0.5)
         # with(res_ARPE19_vs_RasV12 [selectedGenes, ],
         #      { points(baseMean,log2FoldChange, col= "dodgerblue", cex=1,
         #               lwd=2)
         #        text(baseMean,log2FoldChange,
         #             selectedGenes, pos=2, col="dodgerblue")})
         # with(res_ARPE19_vs_RasV12 [Ras_genes, ],
         #      { points(baseMean,log2FoldChange, col= "dodgerblue", cex=1,
         #               lwd=2)
         #        text(baseMean,log2FoldChange,
         #             Ras_genes, pos=2, col="dodgerblue")})
       })
       
    #MAplots ARPE19 vs MekDD 
    output$MAplot3 <- renderPlot ({
       print("rendering plot: MAplot ARPE19 vs MekDD")
       ##ARPE19 vs MekDD plots##
       par(mfrow=c(1,1))
       #print(input$sample1)
       plotMA(res_ARPE19_vs_MekDD, main="ARPE19 vs MekDD", ylim = c(-20,20),
              ylab = "log fold change (ratio of normalized ARPE19 / MekDD)",
              xlab = "means of normalized counts",
              cex.main= 2,
              cex= 0.5,
              alpha= 0.5)
       # with(res_ARPE19_vs_MekDD [selectedGenes, ],
       #      { points(baseMean,log2FoldChange, col= "dodgerblue", cex=1,
       #               lwd=2)
       #        text(baseMean,log2FoldChange,
       #             selectedGenes, pos=2, col="dodgerblue")})
       # with(res_ARPE19_vs_MekDD [Mek_genes, ],
       #      { points(baseMean,log2FoldChange, col= "dodgerblue", cex=1,
       #               lwd=2)
       #        text(baseMean,log2FoldChange, Mek_genes, pos=2, col="dodgerblue")})
       
       })
      
    #MAplots ARPE19 vs Aktmyr  
    output$MAplot4 <- renderPlot ({
      print("rendering plot: MAplot ARPE19 vs Akymyr")
       ##ARPE19 vs Aktmyr plots##
       par(mfrow=c(1,1))
       #print(input$sample1)
       plotMA(res_ARPE19_vs_Aktmyr, main="ARPE19 vs Aktmyr ", ylim = c(-20,20),
              ylab = "log fold change (ratio of normalized ARPE19 / Aktmyr)",
              xlab = "means of normalized counts",
              cex.main= 2,
              cex= 0.5,
              alpha= 0.5)
       # with(res_ARPE19_vs_Aktmyr [selectedGenes, ],
       #      { points(baseMean,log2FoldChange, col= "dodgerblue", cex=1,
       #               lwd=2)
       #        text(baseMean,log2FoldChange, selectedGenes, pos=2, col="dodgerblue")})
       # with(res_ARPE19_vs_Aktmyr [Akt_genes, ],
       #      { points(baseMean,log2FoldChange, col= "dodgerblue", cex=1,
       #               lwd=2)
       #        text(baseMean,log2FoldChange, Akt_genes, pos=2, col="dodgerblue")})


    })
  
    #heatmap showing mean counts of significantly changing genes of interest
    output$pheatmap1<- renderPlot({
      print("rendering plot")
      filtered2 = genes_of_interest_means
      melted2 = melt(genes_of_interest_means)
      colnames(melted2) <- c("Gene","sample","counts")
      print(input$sample)
      filtered2 = melted2[melted2$Gene %in% input$Gene & melted2$sample %in% input$sample,]
      print(filtered2)
      ggplot(filtered2, 
             aes(x=sample,y=Gene,
                 group=counts,
                 col=Gene)) + 
        ggtitle ("Mean counts of significantly changing genes of interest") +
        geom_raster(aes(fill=log10(counts))) +
        scale_fill_gradient(low = "green", high = "red")+
        theme_classic()
      })
    
    #heatmap showing mean counts for ALL significantly changing genes of interest
    output$pheatmap2<- renderPlot({
      print("rendering plot")
      filtered3 = means_of_changing_genes
      melted3 = melt(means_of_changing_genes)
      colnames(melted3) <- c("Gene","sample","counts")
      print(input$sample1)
      filtered3 = melted3[melted3$Gene %in% input$All & melted3$sample %in% input$sample1,]
      print(filtered3)
      ggplot(filtered3, 
             aes(x=sample,y=Gene,
                 group=counts,
                 col=Gene)) + 
        geom_raster(aes(fill=log10(counts))) +
        ggtitle ("Means counts for all significantly changing genes")+
        theme_classic()
      })
    
    #Plotcounts
    output$boxplot1<- renderPlot ({
      print("rendering plot")
      print(input$Gene2)
      #Reorder samples to match experimental design
      dds$sample <- factor(dds$sample, levels=c("ARPE19", "T53D4", "RasV12", "Aktmyr", "MekDD"))
      dds$sample
      #AKT1
      plotCounts(dds, gene=which(rownames(dds)=="AKT1"),intgroup = c("sample"),       cex.main=2, cex=1.5, xlab= "Sample", returnData = T)
      pc_AKT1<-plotCounts(dds, gene=which(rownames(dds)=="AKT1"),intgroup =          c("sample"), cex.main=2, cex=1.5, xlab= "Sample", returnData = T)
      ggplot (pc_AKT1,aes(x=sample,y=count)) +
        geom_boxplot(aes(fill=sample, alpha=0.9))+ stat_summary( geom="point", shape=20, size=5,         color="red", fill="red") +
        geom_jitter()+scale_y_log10() + 
        ggtitle("AKT1 expression")
    
    # #heatmap showing mean counts for ALL significantly changing genes
    # output$boxplot1<- renderPlot({
    #   print("rendering plot")
    #   filtered4 = dds
    #   melted4 = melt(dds)
    #   colnames(melted4) <- c("Gene","sample","counts")
    #   print(input$sample2)
    #   print(input$gene2)
    #   filtered4 = melted4[melted4$Gene %in% input$All & melted4$sample %in% input$sample2,]
    #   print(filtered4)
    #   plotCounts(dds, gene=which(rownames(normalized_genecounts)=="AKT1"),intgroup = c("sample"), cex.main=2, cex=1.5, xlab= "Sample", returnData = T)
    #   pc_AKT1<-plotCounts(dds, gene=which(rownames(normalized_genecounts)=="AKT1"),intgroup = c("sample"), cex.main=2, cex=1.5, xlab= "Sample", returnData = T)
    #   ggplot (pc_BUB1,aes(x=sample,y=count)) +
    #     geom_boxplot(aes(fill=sample, alpha=0.9))+ stat_summary( geom="point", shape=20, size=5, color="red", fill="red") +
    #     geom_jitter()+scale_y_log10()
    # })
    
     })
    })
  }
```


```{r App}
shinyApp(ui=ui, server=server)
```



